In [3]:
import numpy as np

# Step 1: Seed
np.random.seed(888)

# Step 2: Normal distribution (1D, size 100)
arr_normal = np.random.randn(100)

# Step 3: Uniform integers 1–10 (2D, 8x8)
arr_uniform_2d = np.random.randint(1, 11, size=(8, 8))

# Step 4: Uniform integers 1–17 (3D, 4x2x5)
arr_uniform_3d = np.random.randint(1, 18, size=(4, 2, 5))

print("normal array", arr_normal[:5])      # peek first 5 numbers

print("2d", arr_uniform_2d)      # 8x8 grid
print("3d", arr_uniform_3d)      # 3D "cube"


normal array [-0.17620087  0.18887636  0.82674718 -0.03244731 -0.65249942]
2d [[ 9  8  4  6  9  1  3  2]
 [ 3  9  9  5  4  7  2  8]
 [ 5  6  9  1  1  6  8  7]
 [ 7  1  4  1 10  4  3  5]
 [ 5 10  1 10  7 10  6  1]
 [ 6  8  7  4  6 10  3  5]
 [ 4 10  7  9  9 10  9  9]
 [ 5  3  2 10  8  5  5  3]]
3d [[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2 15 13]
  [12 14  6 14  2]]]
