In [1]:
import numpy as np

# -------------------------------
# Exercise 6: Broadcasting & Slicing
# -------------------------------

# 1. Generate a 9x9 array filled with ones
arr = np.ones((9, 9), dtype=np.int8)
print("9x9 Ones Array:\n", arr, "\n")

# 2. Modify using slicing to create maze-like pattern
arr[1:-1, 1:-1] = 0   # inner block zeros
arr[2:-2, 2:-2] = 1   # restore middle block of ones
arr[3:-3, 3:-3] = 0   # carve inner zeros
arr[4, 4] = 1         # restore center to one

print("Maze-like Pattern:\n", arr, "\n")

# 3. Broadcasting example
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8).reshape(-1, 1)  # column vector
array_2 = np.array([1, 2, 3], dtype=np.int8)                       # row vector
result = array_1 * array_2

print("Broadcasted Multiplication:\n", result)


9x9 Ones Array:
 [[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]] 

Maze-like Pattern:
 [[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]] 

Broadcasted Multiplication:
 [[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]
